# Generated by Django 2.1.5 on 2019-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
